services:

  rallly:
    image: lukevella/rallly:latest
    restart: always
    environment:
      - VIRTUAL_HOST=rallly.jeschek.eu
      - LETSENCRYPT_HOST=rallly.jeschek.eu
    env_file:
      - rallly.env
    networks:
      - proxy
      - default
      - db

networks:
  proxy:
    external: true
  db:
    external: true
