services:

  app:
    image: actualbudget/actual-server:latest
    restart: unless-stopped

    environment:
      VIRTUAL_HOST: actual.jeschek.eu
      LETSENCRYPT_HOST: actual.jeschek.eu

    volumes:
      - ./data:/data

    networks:
      - proxy


networks:
  proxy:
    external: true
