version: '3.8'
services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - postgres.env
    ports:
      - '5432:5432'
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - proxy_default
      - default
    environment:
      - VIRTUAL_HOST=pg.jeschek.eu
      - LETSENCRYPT_HOST=pg.jeschek.eu
      - LETSENCRYPT_EMAIL=dev@jeschek.eu
      - PGADMIN_DEFAULT_EMAIL=root@jeschek.eu
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  proxy_default:
    external: true
