version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: joshuajeschek
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    networks:
      - proxy_default
      - default
    environment:
      - VIRTUAL_HOST=db.jeschek.eu
      - LETSENCRYPT_HOST=db.jeschek.eu
      - LETSENCRYPT_EMAIL=dev@jeschek.eu
      - PGADMIN_DEFAULT_EMAIL=dev@jeschek.eu
      - PGADMIN_DEFAULT_PASSWORD=root
networks:
  proxy_default:
    external: true
